create table Ministerio (id int identity(1, 1) not null, nombreMinisterio varchar(100) not null unique, primary key (id));
create table Profesor (id int identity(1, 1) not null, nombreProfesor varchar(50) not null, apellidosProfesor varchar(50) not null, primary key (id));
create table Tema (id int identity(1, 1) not null, titulo varchar(255) not null unique, descripcion varchar(255) null, primary key (id));
create table GastoFinanzas (id int identity(1, 1) not null, ConceptoGastoid int not null, SubconceptoGastoid int null, descripcion varchar(255) not null, importe money not null, fecha datetime not null, TipoMonedaid int not null, Usuarioid int not null, Cuentasid int not null, primary key (id));
create table IngresoFinanzas (id int identity(1, 1) not null, ConceptoIngresoid int not null, descripcion varchar(255) null, importe money not null, fecha datetime not null, TipoMonedaid int not null, Usuarioid int not null, Cuentasid int not null, primary key (id));
create table Taller (id int identity(1, 1) not null, Temaid int not null, fecha datetime not null, primary key (id));
create table Usuario (id int identity(1, 1) not null, nombreUsuario varchar(100) not null unique, pass varchar(50) not null, Rolid int not null, primary key (id));
create table Rol (id int identity(1, 1) not null, nombreRol varchar(50) not null unique, primary key (id));
create table ConceptoGasto (id int identity(1, 1) not null, concepto varchar(255) not null unique, primary key (id));
create table SubconceptoGasto (id int identity(1, 1) not null, subconcepto varchar(255) not null unique, primary key (id));
create table Profesor_Taller (Profesorid int not null, Tallerid int not null, primary key (Profesorid, Tallerid));
create table Ministerio_Taller (Ministerioid int not null, Tallerid int not null, primary key (Ministerioid, Tallerid));
create table GastoTaller (id int identity(1, 1) not null, ConceptoGastoid int not null, descripcion varchar(255) not null, importe money not null, fecha datetime not null, TipoMonedaid int not null, Usuarioid int not null, Tallerid int not null, primary key (id));
create table IngresoTaller (id int identity(1, 1) not null, descripcion varchar(255) not null, importe money not null, fecha datetime not null, TipoMonedaid int not null, Usuarioid int not null, Tallerid int not null, ConceptoIngresoid int not null, primary key (id));
create table TipoMoneda (id int identity(1, 1) not null, siglas varchar(5) not null unique, moneda varchar(255) not null, primary key (id));
create table ConceptoIngreso (id int identity(1, 1) not null, concepto varchar(255) not null unique, calcularPorciento tinyint not null, primary key (id));
create table Cuentas (id int identity(1, 1) not null, nombre varchar(100) not null unique, TipoMonedaid int not null, descriptcion varchar(255) not null, importe money not null, primary key (id));
create table Persona (id int identity(1, 1) not null, nombre varchar(100) not null, apellido1 varchar(100) null, apellido2 varchar(100) null, ci int null unique, miembro tinyint not null, fechaBautismo datetime null, fechaConversion datetime null, primary key (id));
create table Diezmo (id int identity(1, 1) not null, Personaid int not null, TipoMonedaid int not null, importe money not null, fecha datetime not null, Usuarioid int not null, primary key (id));
create table UnidadMedida (id int identity(1, 1) not null, siglas varchar(10) not null unique, unidad varchar(50) not null unique, primary key (id));
create table Producto (id int identity(1, 1) not null, nombre varchar(255) not null unique, descripcion varchar(255) null, UnidadMedidaid int not null, primary key (id));
create table TipoAyuda (id int identity(1, 1) not null, tipo varchar(100) not null unique, descripcion varchar(255) null, primary key (id));
create table Almacen (id int identity(1, 1) not null, cantidad int not null, precio money not null, Productoid int not null, primary key (id));
create table CompraProducto (id int identity(1, 1) not null, fecha datetime not null, precio money not null, cantidad int not null, Productoid int not null, Usuarioid int not null, primary key (id));
create table SalidaAlmacen (id int identity(1, 1) not null, fecha datetime not null, cantidad int not null, Almacenid int not null, TipoAyudaid int not null, Usuarioid int not null, primary key (id));
alter table Usuario add constraint FKUsuario38509 foreign key (Rolid) references Rol (id);
alter table Profesor_Taller add constraint FKProfesor_T339377 foreign key (Profesorid) references Profesor (id);
alter table Profesor_Taller add constraint FKProfesor_T702457 foreign key (Tallerid) references Taller (id);
alter table Taller add constraint FKTaller862524 foreign key (Temaid) references Tema (id);
alter table Ministerio_Taller add constraint FKMinisterio809383 foreign key (Ministerioid) references Ministerio (id);
alter table Ministerio_Taller add constraint FKMinisterio190115 foreign key (Tallerid) references Taller (id);
alter table GastoFinanzas add constraint FKGastoFinan990835 foreign key (SubconceptoGastoid) references SubconceptoGasto (id);
alter table GastoFinanzas add constraint FKGastoFinan245216 foreign key (ConceptoGastoid) references ConceptoGasto (id);
alter table IngresoTaller add constraint FKIngresoTal903281 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table GastoTaller add constraint FKGastoTalle798370 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table IngresoTaller add constraint FKIngresoTal593138 foreign key (Usuarioid) references Usuario (id);
alter table GastoTaller add constraint FKGastoTalle676799 foreign key (Usuarioid) references Usuario (id);
alter table GastoTaller add constraint FKGastoTalle286316 foreign key (ConceptoGastoid) references ConceptoGasto (id);
alter table GastoTaller add constraint FKGastoTalle27128 foreign key (Tallerid) references Taller (id);
alter table IngresoTaller add constraint FKIngresoTal674524 foreign key (Tallerid) references Taller (id);
alter table IngresoFinanzas add constraint FKIngresoFin191449 foreign key (ConceptoIngresoid) references ConceptoIngreso (id);
alter table IngresoFinanzas add constraint FKIngresoFin373077 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table GastoFinanzas add constraint FKGastoFinan641687 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table IngresoTaller add constraint FKIngresoTal661244 foreign key (ConceptoIngresoid) references ConceptoIngreso (id);
alter table IngresoFinanzas add constraint FKIngresoFin123343 foreign key (Usuarioid) references Usuario (id);
alter table GastoFinanzas add constraint FKGastoFinan854732 foreign key (Usuarioid) references Usuario (id);
alter table Cuentas add constraint FKCuentas36608 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table GastoFinanzas add constraint FKGastoFinan518235 foreign key (Cuentasid) references Cuentas (id);
alter table IngresoFinanzas add constraint FKIngresoFin249625 foreign key (Cuentasid) references Cuentas (id);
alter table Diezmo add constraint FKDiezmo288517 foreign key (Personaid) references Persona (id);
alter table Diezmo add constraint FKDiezmo435092 foreign key (TipoMonedaid) references TipoMoneda (id);
alter table Producto add constraint FKProducto768955 foreign key (UnidadMedidaid) references UnidadMedida (id);
alter table Almacen add constraint FKAlmacen795546 foreign key (Productoid) references Producto (id);
alter table CompraProducto add constraint FKCompraProd505569 foreign key (Productoid) references Producto (id);
alter table SalidaAlmacen add constraint FKSalidaAlma377447 foreign key (Almacenid) references Almacen (id);
alter table SalidaAlmacen add constraint FKSalidaAlma282847 foreign key (TipoAyudaid) references TipoAyuda (id);
alter table SalidaAlmacen add constraint FKSalidaAlma910466 foreign key (Usuarioid) references Usuario (id);
alter table CompraProducto add constraint FKCompraProd845775 foreign key (Usuarioid) references Usuario (id);
alter table Diezmo add constraint FKDiezmo61328 foreign key (Usuarioid) references Usuario (id);
create unique index Ministerio_id on Ministerio (id);
create unique index Profesor_id on Profesor (id);
create unique index Tema_id on Tema (id);
create unique index GastoFinanzas_id on GastoFinanzas (id);
create unique index IngresoFinanzas_id on IngresoFinanzas (id);
create unique index Taller_id on Taller (id);
create unique index Usuario_id on Usuario (id);
create unique index Rol_id on Rol (id);
create unique index ConceptoGasto_id on ConceptoGasto (id);
create unique index SubconceptoGasto_id on SubconceptoGasto (id);
create unique index GastoTaller_id on GastoTaller (id);
create unique index IngresoTaller_id on IngresoTaller (id);
create unique index TipoMoneda_id on TipoMoneda (id);
create unique index ConceptoIngreso_id on ConceptoIngreso (id);
create unique index Cuentas_id on Cuentas (id);
create unique index Persona_id on Persona (id);
create unique index Diezmo_id on Diezmo (id);
create unique index UnidadMedida_id on UnidadMedida (id);
create unique index Producto_id on Producto (id);
create unique index TipoAyuda_id on TipoAyuda (id);
create unique index Almacen_id on Almacen (id);
create unique index CompraProducto_id on CompraProducto (id);
create unique index SalidaAlmacen_id on SalidaAlmacen (id);
