//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.SalidaAlmacen = new HashSet<SalidaAlmacen>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        
        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Precio")]
        [DataType(DataType.Currency)]
        public decimal precio { get; set; }

        public int Productoid { get; set; }
        public int TipoMonedaid { get; set; }
    
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<SalidaAlmacen> SalidaAlmacen { get; set; }

        public override string ToString()
        {
            return Producto.nombre + " (" + precio + " " +TipoMoneda.siglas + ")";
        }
    }
}
