//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoGasto
    {
        public ConceptoGasto()
        {
            this.GastoFinanzas = new HashSet<GastoFinanzas>();
            this.SubconceptoGasto = new HashSet<SubconceptoGasto>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Concepto")]
        [Remote("CheckConcepto", "ConceptoGasto", AdditionalFields = "id", ErrorMessage = "Ya existe este Concepto de Gasto")]
        public string concepto { get; set; }
    
        public virtual ICollection<GastoFinanzas> GastoFinanzas { get; set; }
        public virtual ICollection<SubconceptoGasto> SubconceptoGasto { get; set; }
    }
}
