//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Finanzas.Filters;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoIngreso
    {
        public ConceptoIngreso()
        {
            this.IngresoFinanzas = new HashSet<IngresoFinanzas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Concepto")]
        [Remote("CheckConcepto", "ConceptoIngreso", AdditionalFields = "id", ErrorMessage = "Ya existe este Concepto de Ingreso")]
        public string concepto { get; set; }

        [Display(Name = "Calcular Porciento")]
        public bool calcularPorciento { get; set; }
    
        public virtual ICollection<IngresoFinanzas> IngresoFinanzas { get; set; }
    }
}
