//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public Cuentas()
        {
            this.CompraProducto = new HashSet<CompraProducto>();
            this.GastoFinanzas = new HashSet<GastoFinanzas>();
            this.IngresoFinanzas = new HashSet<IngresoFinanzas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Cuenta")]
        [Remote("CheckCuenta", "Cuenta",AdditionalFields = "id",ErrorMessage = "Ya existe esta cuenta")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Saldo")]
        public decimal importe { get; set; }

        public int TipoMonedaid { get; set; }

        [Display(Name = "Descripcion")]
        public string descriptcion { get; set; }
       
        public bool activo { get; set; }
    
        public virtual ICollection<CompraProducto> CompraProducto { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual ICollection<GastoFinanzas> GastoFinanzas { get; set; }
        public virtual ICollection<IngresoFinanzas> IngresoFinanzas { get; set; }

        public override string ToString()
        {
            return nombre;
        }
    }
}
