//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscuelaDominical
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public System.DateTime fecha { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Asistencia")]
        [Range(0,int.MaxValue,ErrorMessage = "Este campo debe ser positivo")]
        public int asistencia { get; set; }

        public int TemaPredicacionid { get; set; }
        public int Usuarioid { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TemaPredicacion TemaPredicacion { get; set; }
    }
}
