//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Almacen> Almacen { get; set; }
        public DbSet<CategoriaPersona> CategoriaPersona { get; set; }
        public DbSet<CompraProducto> CompraProducto { get; set; }
        public DbSet<ConceptoGasto> ConceptoGasto { get; set; }
        public DbSet<ConceptoIngreso> ConceptoIngreso { get; set; }
        public DbSet<Cuentas> Cuentas { get; set; }
        public DbSet<EscuelaDominical> EscuelaDominical { get; set; }
        public DbSet<GastoFinanzas> GastoFinanzas { get; set; }
        public DbSet<IngresoFinanzas> IngresoFinanzas { get; set; }
        public DbSet<Misiones> Misiones { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<SalidaAlmacen> SalidaAlmacen { get; set; }
        public DbSet<SubconceptoGasto> SubconceptoGasto { get; set; }
        public DbSet<TemaPredicacion> TemaPredicacion { get; set; }
        public DbSet<TipoAyuda> TipoAyuda { get; set; }
        public DbSet<TipoMoneda> TipoMoneda { get; set; }
        public DbSet<UnidadMedida> UnidadMedida { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
