//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoFinanzas
    {
        public int id { get; set; }
        public int Cuentasid { get; set; }
        public int ConceptoIngresoid { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        [Remote("CheckFecha","IngresoFinanza",ErrorMessage = "La fecha no corresponde al mes y año actual del sistema")]
        public System.DateTime fecha { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Importe")]
        [DataType(DataType.Currency)]
        public decimal importe { get; set; }

        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
        
        public int Usuarioid { get; set; }
        public Nullable<int> Personaid { get; set; }
    
        public virtual ConceptoIngreso ConceptoIngreso { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
