//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misiones
    {
        public Misiones()
        {
            this.Personas = new HashSet<Persona>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Lugar")]
        [Remote("CheckMision", "Mision", AdditionalFields = "id", ErrorMessage = "Ya existe esta Mision")]
        public string lugar { get; set; }

        public int Personaid { get; set; }
    
        public virtual Persona Lider { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
    }
}
