//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Almacen = new HashSet<Almacen>();
            this.CompraProducto = new HashSet<CompraProducto>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Producto")]
        [Remote("CheckProducto", "Producto", AdditionalFields = "id", ErrorMessage = "Ya existe este Producto")]
        public string nombre { get; set; }

        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }

        public int UnidadMedidaid { get; set; }
    
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<CompraProducto> CompraProducto { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }

        public override string ToString()
        {
            return nombre;
        }
    }
}
