//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaAlmacen
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Fecha de Salida")]
        [DataType(DataType.Date)]
        [Remote("CheckFecha", "SalidaAlmacen", ErrorMessage = "La fecha no corresponde al mes y año actual del sistema")]
        public System.DateTime fecha { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Cantidad")]
        [Remote("CheckAlmacen", "SalidaAlmacen", AdditionalFields = "Almacenid,id", ErrorMessage = "Este almacen no tiene esa cantidad de producto")]
        public int cantidad { get; set; }

        public int Almacenid { get; set; }
        public int TipoAyudaid { get; set; }
        public int Usuarioid { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual TipoAyuda TipoAyuda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
