//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubconceptoGasto
    {
        public SubconceptoGasto()
        {
            this.GastoFinanzas = new HashSet<GastoFinanzas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Subconcepto de Gasto")]
        [Remote("CheckSubconcepto", "SubconceptoGasto", AdditionalFields = "id", ErrorMessage = "Ya existe este Subconcepto")]
        public string subconcepto { get; set; }

        public int ConceptoGastoid { get; set; }
    
        public virtual ConceptoGasto ConceptoGasto { get; set; }
        public virtual ICollection<GastoFinanzas> GastoFinanzas { get; set; }

        public override string ToString()
        {
            return subconcepto;
        }
    }
}
