//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMoneda
    {
        public TipoMoneda()
        {
            this.Cuentas = new HashSet<Cuentas>();
            this.Almacen = new HashSet<Almacen>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Siglas")]
        [Remote("CheckSiglas", "TipoMoneda", AdditionalFields = "id", ErrorMessage = "Ya existe una Moneda con estas siglas")]
        public string siglas { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Moneda")]
        [Remote("CheckMoneda", "TipoMoneda", AdditionalFields = "id", ErrorMessage = "Ya existe esta Moneda")]
        public string moneda { get; set; }
    
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual ICollection<Almacen> Almacen { get; set; }

        public override string ToString()
        {
            return siglas;
        }
    }
}
