//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMedida
    {
        public UnidadMedida()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Siglas")]
        [Remote("CheckSiglas", "UnidadMedida", AdditionalFields = "id", ErrorMessage = "Ya existe una unidad de medida con estas siglas")]
        public string siglas { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Unidad de Medida")]
        [Remote("CheckUnidad", "UnidadMedida", AdditionalFields = "id", ErrorMessage = "Ya existe esta Unidad de Medida")]
        public string unidad { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
