//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.CompraProducto = new HashSet<CompraProducto>();
            this.EscuelaDominical = new HashSet<EscuelaDominical>();
            this.GastoFinanzas = new HashSet<GastoFinanzas>();
            this.IngresoFinanzas = new HashSet<IngresoFinanzas>();
            this.SalidaAlmacen = new HashSet<SalidaAlmacen>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Usuario")]
        [Remote("CheckUsuario","Usuario",AdditionalFields = "id", ErrorMessage = "Ya existe este usuario")]
        public string nombreUsuario { get; set; }

        [Required(ErrorMessage = "Este dato es Obligatorio")]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "La {0} debe tener al menos {2} caracteres.", MinimumLength = 8)]
        public string pass { get; set; }

        public int Rolid { get; set; }

        [Display(Name = "Activo")]
        public bool activo { get; set; }
    
        public virtual ICollection<CompraProducto> CompraProducto { get; set; }
        public virtual ICollection<EscuelaDominical> EscuelaDominical { get; set; }
        public virtual ICollection<GastoFinanzas> GastoFinanzas { get; set; }
        public virtual ICollection<IngresoFinanzas> IngresoFinanzas { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<SalidaAlmacen> SalidaAlmacen { get; set; }
    }
}
